Homework 4 complete
Kiberfilin/My_Application pull request #3
Opened 2021-01-16 11:21 UTC by Kiberfilin

Homework 4 completed

2021-01-19 20:18 UTC, pcfaktor requested changes
- You should use View Binding. It makes the code more clear;
-  Remove unused Activity;

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesDetails.kt
> +
You should change the color of view instead of changing the resource.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        val recyclerView = rootView.findViewById<RecyclerView>(R.id.movie_list_rv)
Move data to another class (ex. DataSource).

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +
Repeated function. You can move it in util.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +
ViewHolder needs to be as simple as possible. Needs to handle the click events in onCreateViewHolder. In the current implementation,  the instance of the listener will be created on each click event.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        recyclerView.adapter =
lateinit onMovieCardClickAction is not initializing when configuration changed. And crash happens.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        recyclerView.layoutManager =
You can set different span count according to orientation.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +        movieCardBackgroundPicture.setImageResource(item.movieCardBacgroundPicture)
Again, use color instead of a resource.

2021-01-19 20:18 UTC, pcfaktor commented on app/src/main/res/layout/view_holder_movie.xml
> +
Why you use CardView with an inner container for this simple element?

2021-01-21 21:41 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        recyclerView.layoutManager =
Могу, конечно, но седьмой пункт дз прямо говорит, что столбцов должно быть 2

2021-01-21 21:44 UTC, Kiberfilin commented on app/src/main/res/layout/view_holder_movie.xml
> +
А каким  ещё образом мне установить background у кардвью если не при помощи какого-нибудь другого лаяута? С помощью кардвью закругляем углы, а с помощью вложенного лаяута красим в нужный цвет.

2021-01-21 22:59 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +
И будет потом безболезненно убран сборщиком мусора, так как на него ссылка во вьюхолдере не храниться. А в методе онкреейтвьюхолдер пока ещё нет экземпляра movie, который нужно будет передать дальше во фрагмент с деталями.

2021-01-21 23:07 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesDetails.kt
> +
Решено в комите Homework 4 complete; small fixes

2021-01-21 23:08 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        val recyclerView = rootView.findViewById<RecyclerView>(R.id.movie_list_rv)
Решено в комите Homework 4 complete; small fixes

2021-01-21 23:08 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +
Решено в комите Homework 4 complete; small fixes

2021-01-21 23:09 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesList.kt
> +        recyclerView.adapter =
Решено в комите Homework 4 complete; small fixes

2021-01-21 23:09 UTC, Kiberfilin commented on app/src/main/java/ru/cybereagleowl/myapplication/MoviesListAdapter.kt
> +        movieCardBackgroundPicture.setImageResource(item.movieCardBacgroundPicture)
Решено в комите Homework 4 complete; small fixes

2021-01-24 18:41 UTC, Kiberfilin commented on app/src/main/res/layout/view_holder_movie.xml
> +
Решено в Homework 4 complete; small fixes 2

2021-01-26 06:43 UTC, pcfaktor approved these changes

2021-01-26 06:43 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesDetails.kt
> +            backIcon.setOnClickListener(onBackClick)
You can make textView field wide and listen to clicks only on it.

2021-01-26 06:43 UTC, pcfaktor commented on app/src/main/java/ru/cybereagleowl/myapplication/FragmentMoviesDetails.kt
> +    private val binding get() = _binding!!
Need to set a null in _binding at the onDestroyView().

2021-02-13 05:55 UTC, merged